# Don't print a new line at the start of the prompt

add_newline = false


format = """

$directory  $git_branch $git_status 

$character"""


# Prompt symbols

[character]

success_symbol = "[  î©± ï‹](bold fg:#CBA6F7)"

error_symbol   = "[  ï€ ï‹](bold fg:#F38BA8)"    # red


# Disable the package module

[package]

disabled = true


[git_branch]

style = "bg:#CBA6F7 fg:#1E1E2E"   # purple background, dark text

symbol = "ó°˜¬"

truncation_length = 6

truncation_symbol = ""

format = "[î‚¶](bold fg:#CBA6F7)[$symbol $branch(:$remote_branch)](fg:#1E1E2E bg:#CBA6F7)[î‚´ ](bold fg:#CBA6F7)"


[git_commit]

commit_hash_length = 4

tag_symbol = "ï’¶ "


[git_state]

format = '[\($state( $progress_current of $progress_total)\)]($style) '

cherry_pick = "[ğŸ’ PICKING](bold #F38BA8)"



[git_status]

conflicted = '( $countâš”ï¸)(#FF5555)'
ahead      = '( $countğŸğŸ’¨)(#55FF55)'
behind     = '( $countğŸ¢)(#FFFF55)'
diverged   = '( $countğŸ”€)(#FF55FF)'
untracked  = '( $countğŸ†•)(#55FFFF)'
stashed    = '( $countğŸ“¦)(#AAAAFF)'
modified   = '( $countâœï¸)(#FFA500)'
staged     = '[ ++($count)](#ABE9B3)'
renamed    = '( $countâœï¸)(#55AAFF)'
deleted    = '( $countğŸ—‘)(#FF5555)'





[hostname]

ssh_only = true

format = "[â€¢$hostname](bg:#F9E2AF bold fg:#1E1E2E)[î‚´](bold fg:#F9E2AF)"  # peach background

trim_at = ".companyname.com"

disabled = false


[line_break]

disabled = false


[memory_usage]

disabled = true

threshold = -1

symbol = " "

style = "bold dimmed #ABE9B3"


[time]

disabled = true

format = 'ğŸ•™[\[ $time \]]($style) '

time_format = "%T"


[username]

style_user = "bold bg:#CBA6F7 fg:#1E1E2E"   # segment background and text

style_root = "bold bg:#F38BA8 fg:#1E1E2E"

format = "[î‚¶](fg:#CBA6F7)[$user]($style)[î‚´](fg:#CBA6F7)"

show_always = true



[directory]

home_symbol = " ï‘­ "

read_only = " ï‘– "

style = "bg:#F5C2E7 fg:#1E1E2E"             # pink background

truncation_length = 0
truncate_to_repo = true



format = '[î‚¶](bold fg:#F5C2E7)[ó°‰‹ $path]($style)[î‚´](bold fg:#F5C2E7)'


[directory.substitutions]

"Desktop" = " ï’© "

"Documents" = " ï’¥ "

"Downloads" = " ï‰ "

"Music" = " ó°ˆ "

"Pictures" = " ï "

"Videos" = " ï”¬ "

"GitHub" = " ó°Š¤ "


[cmd_duration]

disabled = true

